
--------------------------------------------------------------
-- Database table removal script

-- Auto-Generated by QSEE-SuperLite (c) 2001-2004 QSEE-Technologies Ltd.

-- note: spaces within table names have been replaced by underscores (_)

-- Target DB: SQL2

-- Entity Model :Entity Relationship Diagram

-- Use this script to drop the tables created by -
--   'D:\British\Oracle\assignment\Assignment\Assignement stuff\task_2\SQL.sql'

-- Dropping a table has the effect of removing it from the Database.  All existing data is lost
-- as well as the definition of the table itself (stored as meta-data).  Dropping the tables allows
-- them to be re-created within the Database, even if they already exist.


--------------------------------------------------------------

-- Drop tables --

DROP TABLE factTable;

DROP TABLE Customer_Dim;

DROP TABLE Product_Dim;

DROP TABLE Time_Dim;

DROP TABLE Agent_Dim;

DROP TABLE Order_Dim;

DROP TABLE Branch_Dim;

DROP TABLE Country_Dim;


--------------------------------------------------------------
-- End of DDL DROP file auto-generation
--------------------------------------------------------------
