--------------------------------------------------------------
-- Database creation Script
-- Auto-Generated by QSEE-SuperLite (c) 2001-2004 QSEE-Technologies Ltd.
-- Verbose generation: ON
-- note: spaces within table/column names have been replaced by underscores (_)
-- Target DB: SQL2
-- Entity Model :Entity Relationship Diagram

--------------------------------------------------------------
DROP table time_dim cascade constraints;
DROP table location_dim cascade constraints;
DROP table fact_claim cascade constraints;

--------------------------------------------------------------
-- Table Creation --

-- Each entity on the model is represented by a table that needs to be created within the Database.
-- Within SQL new tables are created using the CREATE TABLE command.
-- When a table is created its name and its attributes are defined.
-- The values of which are derived from those specified on the model.
-- Certain constraints are sometimes also specified, such as identification of primary keys.
-- Create a Database table to represent the "FACT_CLAIM" entity.
CREATE TABLE FACT_CLAIM(
	report_id	INTEGER NOT NULL,
	fk1_time_id	INTEGER NOT NULL,
	fk2_location_id	INTEGER NOT NULL,
total_claim_location	INTEGER,
	-- Specify the PRIMARY KEY constraint for table "FACT_CLAIM".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_FACT_CLAIM PRIMARY KEY (report_id)
);
-- Create a Database table to represent the "time_dim" entity.
CREATE TABLE time_dim(
	time_id	INTEGER NOT NULL,
	the_year	INTEGER,
	-- Specify the PRIMARY KEY constraint for table "time_dim".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_time_dim PRIMARY KEY (time_id)
);
-- Create a Database table to represent the "location_dim" entity.
CREATE TABLE location_dim(
	location_id	INTEGER NOT NULL,
	state	VARCHAR(15),
	-- Specify the PRIMARY KEY constraint for table "location_dim".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_location_dim PRIMARY KEY (location_id)
);

--------------------------------------------------------------
-- Alter Tables to add fk constraints –
